name: eds_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.0.15
  fluttertoast: ^8.2.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  build_runner: ^2.4.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
